// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package protos

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Operands struct {
	FirstOperand         float32  `protobuf:"fixed32,1,opt,name=first_operand,json=firstOperand,proto3" json:"first_operand,omitempty"`
	SecondOperand        float32  `protobuf:"fixed32,2,opt,name=second_operand,json=secondOperand,proto3" json:"second_operand,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Operands) Reset()         { *m = Operands{} }
func (m *Operands) String() string { return proto.CompactTextString(m) }
func (*Operands) ProtoMessage()    {}
func (*Operands) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *Operands) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Operands.Unmarshal(m, b)
}
func (m *Operands) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Operands.Marshal(b, m, deterministic)
}
func (m *Operands) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Operands.Merge(m, src)
}
func (m *Operands) XXX_Size() int {
	return xxx_messageInfo_Operands.Size(m)
}
func (m *Operands) XXX_DiscardUnknown() {
	xxx_messageInfo_Operands.DiscardUnknown(m)
}

var xxx_messageInfo_Operands proto.InternalMessageInfo

func (m *Operands) GetFirstOperand() float32 {
	if m != nil {
		return m.FirstOperand
	}
	return 0
}

func (m *Operands) GetSecondOperand() float32 {
	if m != nil {
		return m.SecondOperand
	}
	return 0
}

type Result struct {
	Result               float32  `protobuf:"fixed32,1,opt,name=result,proto3" json:"result,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetResult() float32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func (m *Result) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Operands)(nil), "protos.Operands")
	proto.RegisterType((*Result)(nil), "protos.Result")
}

func init() {
	proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626)
}

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 181 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x03, 0x53, 0xc5, 0x4a, 0x61,
	0x5c, 0x1c, 0xfe, 0x05, 0xa9, 0x45, 0x89, 0x79, 0x29, 0xc5, 0x42, 0xca, 0x5c, 0xbc, 0x69, 0x99,
	0x45, 0xc5, 0x25, 0xf1, 0xf9, 0x10, 0x11, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xa6, 0x20, 0x1e, 0xb0,
	0x20, 0x54, 0x95, 0x90, 0x2a, 0x17, 0x5f, 0x71, 0x6a, 0x72, 0x7e, 0x5e, 0x0a, 0x5c, 0x15, 0x13,
	0x58, 0x15, 0x2f, 0x44, 0x14, 0xaa, 0x4c, 0xc9, 0x8a, 0x8b, 0x2d, 0x28, 0xb5, 0xb8, 0x34, 0xa7,
	0x44, 0x48, 0x8c, 0x8b, 0xad, 0x08, 0xcc, 0x82, 0x1a, 0x07, 0xe5, 0x09, 0x49, 0x70, 0xb1, 0xe7,
	0xa6, 0x16, 0x17, 0x27, 0xa6, 0xa7, 0x82, 0x4d, 0xe0, 0x0c, 0x82, 0x71, 0x8d, 0x6c, 0xb8, 0x04,
	0x9d, 0x13, 0x73, 0x92, 0x4b, 0x73, 0x12, 0x4b, 0xf2, 0x8b, 0x82, 0x21, 0xce, 0x16, 0x52, 0xe7,
	0x62, 0x76, 0x4c, 0x49, 0x11, 0x12, 0x80, 0xb8, 0xbf, 0x58, 0x0f, 0xe6, 0x6a, 0x29, 0x3e, 0x98,
	0x08, 0xc4, 0xbe, 0x24, 0x88, 0xcf, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x2f, 0xc8, 0x61,
	0xab, 0xf1, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CalculatorServiceClient is the client API for CalculatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CalculatorServiceClient interface {
	Add(ctx context.Context, in *Operands, opts ...grpc.CallOption) (*Result, error)
}

type calculatorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCalculatorServiceClient(cc grpc.ClientConnInterface) CalculatorServiceClient {
	return &calculatorServiceClient{cc}
}

func (c *calculatorServiceClient) Add(ctx context.Context, in *Operands, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/protos.CalculatorService/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CalculatorServiceServer is the server API for CalculatorService service.
type CalculatorServiceServer interface {
	Add(context.Context, *Operands) (*Result, error)
}

// UnimplementedCalculatorServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCalculatorServiceServer struct {
}

func (*UnimplementedCalculatorServiceServer) Add(ctx context.Context, req *Operands) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}

func RegisterCalculatorServiceServer(s *grpc.Server, srv CalculatorServiceServer) {
	s.RegisterService(&_CalculatorService_serviceDesc, srv)
}

func _CalculatorService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Operands)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculatorServiceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.CalculatorService/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculatorServiceServer).Add(ctx, req.(*Operands))
	}
	return interceptor(ctx, in, info, handler)
}

var _CalculatorService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.CalculatorService",
	HandlerType: (*CalculatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _CalculatorService_Add_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
